### ISSUE TITLE
Broken Prolog syntax

### ISSUE THREAD

**Issue by fraaaaa4** [fraaaaa4/logix#4]
Add ' ' literal string syntax
Add variables syntax
Fix - syntax
When opening a file sometimes it doesn't apply the syntax
And add stuff for "40+2" syntax

**Comment by fraaaaa4** [comment]
parent(Parent, Child) :- mother(Parent, Child).

mother doesn't get formatted

**Comment by fraaaaa4** [comment]
Add syntax highlighting for \=

**Comment by fraaaaa4** [comment]
Finally fixed comment sintax

**Comment by fraaaaa4** [comment]
Just kidding, when writing a keyword it formats everything before

**Comment by fraaaaa4** [comment]
Partially fixed - moved all the syntax highlighting from an XML file to variables inside MDIParent1.cs

Problem: syntax highlighting for words such as functions or variables doesn't work, for now it uses a hybrid of XML and code syntax

**Comment by fraaaaa4** [comment]
Add =@= syntax, =< etc

**Comment by fraaaaa4** [comment]
Swap the forecolor and backColor thing in dash in settings

**Comment by fraaaaa4** [comment]
Finally I can say that, **the Prolog syntax is fully working!** 
![immagine](https://github.com/fraaaaa4/logix/assets/87281326/6a4e01a9-24e8-4385-a599-af40ecaae804)

Fully moved to the CurrentTB_TextChanged(TextEventArgs e) method and applyPrologSyntax(e), it's working wonderfully.
@fedeDongio

**Comment by fedeDongio** [comment]
Well done, looks great!

**Comment by fraaaaa4** [comment]
Add =.., var(), functor(), arg() particular syntax

**Comment by fraaaaa4** [comment]
Add particular syntaxes for tests:

:- colour the entire line
assert, dynamic

**Comment by fraaaaa4** [comment]
Fix the fact that ' ' stuff isn't formatted differently
